add component header and connect zustand
vkarelina/q-stats__frontend pull request #1
Opened 2024-09-11 14:05 UTC by vkarelina

add header component and connect zustand

2024-09-11 14:14 UTC, s-skubedin requested changes

2024-09-11 14:14 UTC, s-skubedin commented on src/App.tsx
> +import Header from "./components/header/Header";
index файл

2024-09-11 14:14 UTC, s-skubedin commented on src/components/header/Header.tsx
именуй в kebab-case

2024-09-11 14:14 UTC, s-skubedin commented on src/components/header/Header.tsx
> +    const target = e.target as HTMLElement;
Используй сужение типов через if
```js
if (!(e.target instanceOf HTMLElement...)) return;
```

2024-09-11 14:14 UTC, s-skubedin commented on src/components/header/Header.tsx
> +      {themes.map((theme, index) => (
Темы приходят с бека. Напиши логику для запроса, но запрашивай у моков

2024-09-11 14:14 UTC, s-skubedin commented on src/store/index.ts
> +        const { user } = get();
у get нет аргументов?
Например, `get('user')`

2024-09-11 14:14 UTC, s-skubedin commented on src/components/header/Header.css
> +  border: 1px solid #ff7f00;
Создай палитру

2024-09-11 14:23 UTC, vkarelina commented on src/store/index.ts
> +        const { user } = get();
аргументов у него нет, максимум можно написать так:
```
getUser: () => get().user
```

2024-09-12 08:05 UTC, s-skubedin approved these changes

2024-09-12 09:57 UTC, merged