Feature/question list
vkarelina/q-stats__frontend pull request #3
Opened 2024-10-01 13:59 UTC by vkarelina

Added a list of questions and the ability to add new custom questions. Added theme for questions.

2024-10-01 14:22 UTC, Daniil-Miroshnikov commented on src/api/api.ts
> +// добавление вопроса
комментарий

2024-10-01 14:26 UTC, ysimakina commented on src/components/sidebar/sidebar.tsx
Файлы с расширением .tsx обычно именуются в PascalCase

2024-10-01 14:27 UTC, Daniil-Miroshnikov commented on src/components/question-list/question-list.tsx
> +import { useRef, useState } from "react";
Одинарные кавычки, настрой eslint

2024-10-01 14:52 UTC, Daniil-Miroshnikov commented on src/api/api.ts
> +export const fetchUsers = () => {
неявный return

2024-10-01 15:01 UTC, vkarelina commented on src/api/api.ts
> +// добавление вопроса
это нужный -.-

2024-10-01 15:05 UTC, Daniil-Miroshnikov commented on src/components/sidebar/sidebar.tsx
>    const usersArr = useUser.use.users();
не используй общие слова, Arr, Data

2024-10-01 15:08 UTC, vkarelina commented on src/components/question-list/question-list.tsx
> +import { useRef, useState } from "react";
У меня двойные во всем проекте

2024-10-02 09:38 UTC, s-skubedin requested changes

2024-10-02 09:38 UTC, s-skubedin commented on src/api/api.ts
> +export const fetchQuestionById = (questionId: number) => {
Можно просто id, по названию и логике функции понятно чей id

2024-10-02 09:38 UTC, s-skubedin commented on src/api/api.ts
> +// добавление вопроса
Иногда добавляются комментарии для пояснения кода
Частые случаи - TODO или JSDoc

2024-10-02 09:38 UTC, s-skubedin commented on src/components/header/header.tsx
> +    if (target instanceof HTMLElement && filter?.name !== target.innerText) {
Используй обратные условия

2024-10-02 09:38 UTC, s-skubedin commented on src/components/header/header.tsx
>      const target = e.target;
Деструктурируй

2024-10-02 09:38 UTC, s-skubedin commented on src/components/question-item/index.ts
> +export { default as QuestionItem } from "./question-item";
Пустая строка

2024-10-02 09:38 UTC, s-skubedin commented on src/components/header/header.tsx
> +          className={filter?.id === topic.id ? "active" : ""}
Используй classNames

2024-10-02 09:38 UTC, s-skubedin commented on src/components/question-item/question-item.css
>  textarea {
Или БЭМ или модульные стили или CSS in JS
Лучше 2

2024-10-02 09:38 UTC, s-skubedin commented on src/components/question-item/question-item.tsx
>        <p>{idx + 1 + "."}</p>
Используй интерполяцию

2024-10-02 09:38 UTC, s-skubedin commented on src/components/question-list/question-list.tsx
> +import { useRef, useState } from "react";
Должны быть одинарные, надо исправить и настроить eslint. Правки eslint должны быть в отдельном PR

2024-10-02 09:38 UTC, s-skubedin commented on src/components/question-list/question-list.tsx
> +  const textQuestion = useRef<string>("");
Типизация избыточна

2024-10-02 09:38 UTC, s-skubedin commented on src/components/question-list/question-list.tsx
> +  const questions = useUser.use.sessia();
sessia - не существует такого слова. Проверяй орфографию

2024-10-02 09:38 UTC, s-skubedin commented on src/components/question-list/question-list.tsx
> +  };
Используй неконтролируемый input

2024-10-02 09:38 UTC, s-skubedin commented on src/components/sidebar/sidebar.tsx
Есть 2 подхода к именованию файла, kebab-case или camelCase + PascalCase.
В академии пишем в camelCase + PascalCase, после выхода в тестовых проектах - kebab-case, на проектах придерживаемся уже имеющегося подхода к написанию кода

2024-10-02 09:38 UTC, s-skubedin commented on src/store/question.ts
> +import { fetchAddQuestion, fetchSession } from "../api/api";
index файл

2024-10-02 12:44 UTC, s-skubedin requested changes

2024-10-02 12:44 UTC, s-skubedin commented on src/components/header/header.tsx
> +    const { target } = e;
e - избыточная переменная

2024-10-02 12:44 UTC, s-skubedin commented on src/components/header/header.tsx
> +          className={filter?.id === topic.id ? "active" : ""}
👀

2024-10-02 12:44 UTC, s-skubedin commented on src/components/question-item/question-item.css
>  textarea {
👀

2024-10-02 12:44 UTC, s-skubedin commented on src/components/sidebar/sidebar.tsx
> +        users.map((user) => (
Используй optional chaining

2024-10-02 12:44 UTC, s-skubedin commented on src/mock-data/index.ts
> +    date: new Date(1727382908935),
Используй читаемые значения, например, `new Date(2024, 9, 2)`

2024-10-04 15:03 UTC, vkarelina commented on src/components/question-list/question-list.tsx
> +import { useRef, useState } from "react";
Хорошо, исправлю в следующем pr

2024-10-04 15:03 UTC, s-skubedin approved these changes

2024-10-07 06:28 UTC, merged