Feature/update question
vkarelina/q-stats__frontend pull request #5
Opened 2024-10-11 08:50 UTC by vkarelina

Added update default questions and display of questions by topic.

2024-10-11 09:00 UTC, ysimakina commented on src/api/index.ts
> +  return questions.filter(
Лучше вынести в переменную и возвращать её

2024-10-11 09:04 UTC, vkarelina commented on src/api/index.ts
> +  return questions.filter(
Это будет избыточная переменная, она не нужна

2024-10-11 09:07 UTC, ysimakina commented on src/pages/main-page.tsx
> +
Второй перенос строки избыточен

2024-10-11 09:21 UTC, ysimakina commented on src/api/index.ts
> +};
Верни пустую строку)

2024-10-11 12:15 UTC, s-skubedin requested changes

2024-10-11 12:15 UTC, s-skubedin commented on src/api/index.ts
> +
Пробел

2024-10-11 12:15 UTC, s-skubedin commented on src/api/index.ts
>        .map(({ date, answer, id }) => ({ date, answer, id }));
reduce

2024-10-11 12:15 UTC, s-skubedin commented on src/api/index.ts
> +    return matchingQuestion ? matchingQuestion : session;
||

2024-10-11 12:15 UTC, s-skubedin commented on src/components/header/header.tsx
> +    if (currentTopic?.name === topicName) return;
Имена топиков - не уникальны. Уникальны - id

2024-10-11 12:15 UTC, s-skubedin commented on src/components/header/header.tsx
> +    const topic = topics?.find((topic) => topic.name === topicName);
Может передавать сам топик? Зачем передавать имя, а потом искать.

2024-10-11 12:15 UTC, s-skubedin commented on src/components/header/header.tsx
>            className={currentTopic?.id === topic.id ? styles.active : ''}
classnames

2024-10-11 12:15 UTC, s-skubedin commented on src/components/question-item/question-item.tsx
> +  };
Функция не мемоизирована, нет необходимости в создании cb, используй state
    setIsEditing(!isEditing);

2024-10-11 12:15 UTC, s-skubedin commented on src/components/question-list/question-list.tsx
> +    useQuestion.use.fetchUpdateDefaultQuestion();
Зачем перенос? Установи длину 100

2024-10-11 12:15 UTC, s-skubedin commented on src/components/sidebar/sidebar.tsx
> +    setUser(userId);
не всегда есть смысл в инвертированных условиях
`if (currentUser?.id !== userId) setUser(userId);` - так короче и более читаемо

2024-10-11 12:15 UTC, s-skubedin commented on src/mock-data/index.ts
> +  },
Одинаковый id

2024-10-11 12:15 UTC, s-skubedin commented on src/pages/main-page.tsx
> +  const [questions, setQuestions] = useState<Question[] | SessionRecord[] | []>([]);
const [questions, setQuestions] = useState<Question[] | SessionRecord[]>([]);

2024-10-11 12:15 UTC, s-skubedin commented on src/pages/main-page.tsx
> +    fetchSession(user.id, topic.id);
if (user & topic) fetchSession(user.id, topic.id);

2024-10-11 12:15 UTC, s-skubedin commented on src/pages/main-page.tsx
> +  }, [user, topic, allQuestions]);
Зачем тут allQuestions

2024-10-11 12:15 UTC, s-skubedin commented on src/store/answers.ts
> +  userAnswers: Answer[] | [];
[] - не нужен

2024-10-14 09:36 UTC, skubedin approved these changes

2024-10-14 09:37 UTC, ysimakina approved these changes

2024-10-14 11:16 UTC, merged