deselect topic & user
vkarelina/q-stats__frontend pull request #6
Opened 2024-10-14 12:44 UTC by vkarelina

Added cancel option for themes and for user.

2024-10-14 13:23 UTC, Daniil-Miroshnikov commented on src/store/user.ts
> +      fetchClearSessia: () => {
опечатка: несуществующее слово "Sessia"

2024-10-14 14:46 UTC, s-skubedin requested changes

2024-10-14 14:46 UTC, s-skubedin commented on src/pages/main-page.tsx
> +    user && topic ? fetchSession(user.id, topic.id) : fetchClearSession()
Используй if

2024-10-14 14:46 UTC, s-skubedin commented on src/components/sidebar/sidebar.tsx
> +  const fetchClearCurrentUser = useUser.use.fetchClearCurrentUser();
Что такое ClearCurrentUser?

2024-10-14 14:50 UTC, vkarelina commented on src/components/sidebar/sidebar.tsx
> +  const fetchClearCurrentUser = useUser.use.fetchClearCurrentUser();
Это метод, который очищает текущего пользователя. Есть массив пользователей. А есть текущий выбранный пользователь.

2024-10-15 06:37 UTC, vkarelina commented on src/components/sidebar/sidebar.tsx
> +  const fetchClearCurrentUser = useUser.use.fetchClearCurrentUser();
ClearCurrentUser это условно то что мы получаем через fetchUser, это просто в сторе метод, который меняет состояние поля обратно на null

2024-10-31 14:51 UTC, vkarelina commented on src/components/sidebar/sidebar.tsx
> +  const fetchClearCurrentUser = useUser.use.fetchClearCurrentUser();
Уже неактуально переписала логику

2024-11-01 07:04 UTC, ysimakina commented on src/api/questions.ts
> +    `http://localhost:5000/users/${userId}/questions?topicId=${topicId}`,
Чтобы не писать каждый раз `http://localhost:5000`, у тебя есть переменная VITE_API_URL

2024-11-01 08:18 UTC, s-skubedin requested changes
По поводу меток можешь посмотреть тут - https://conventionalcomments.org/

2024-11-01 08:18 UTC, s-skubedin commented on .env
**issue (blocking):** `.env` не должен находится в репозитории

2024-11-01 08:18 UTC, s-skubedin commented on package.json
> +    "dev": "vite --port 7000",
**suggestion:** Ты можешь вынести порт в env. Думаю, легче указать порт в конфиге vite

2024-11-01 08:18 UTC, s-skubedin commented on src/App.module.css
> +* {
**note:** В будущем стоит добавить нормализацию и сброс. Normalize.css и Reset.css

2024-11-01 08:18 UTC, s-skubedin commented on src/api/questions.ts
> +    `http://localhost:5000/topic/${id}/questions`,
**issue:** Ты уже используешь инстанс axios, где указала api. Достаточно указывать путь.

2024-11-01 08:18 UTC, s-skubedin commented on src/api/questions.ts
> +  const response: AxiosResponse<Question[]> = await api.get(
**suggestion:** Типизировать лучше через generic в get.

2024-11-01 08:18 UTC, s-skubedin commented on src/api/questions.ts
> +  const response: AxiosResponse<Question[]> = await api.get(
**note:** Строгая типизация не всегда хорошая идея

Хотя на всех проектах так делают. Иногда лучше прописать какой-нибудь serializer/validator, который будет проверять входные данные.

2024-11-01 08:18 UTC, s-skubedin commented on src/api/questions.ts
> +};
**polish:** Тут в целом можно избавиться от async/await
Например
```ts
export const createTopicQuestion = (data: Pick<Question, 'text'>, topicId: number) => ( 
  api.post<Question[]>(`/topic/${topicId}/questions`, data).then((r) => r.data);
)
```

2024-11-01 08:18 UTC, s-skubedin commented on src/api/questions.ts
**praise:** Хорошая идея разбить запросы на файлы. Можно было бы еще сделать re-export через index, главное проверить в таком случае отсутствие цикличной зависимости.

2024-11-01 08:18 UTC, s-skubedin commented on src/components-ui/header/header.tsx
> +          className={classNames({
**polish:** Используй короткое имя для `classNames` - `cn`

2024-11-01 08:18 UTC, s-skubedin commented on src/components-ui/question-item/question-item.module.css
> +  background-color: rgba(240, 248, 255, 0);
**suggestion:** Стоит вынести в палитру

2024-11-01 08:18 UTC, s-skubedin commented on src/components-ui/sidebar/sidebar.tsx
>    const currentUser = useUser.use.user();
**suggestion:** Текущего юзера все равно берешь из стора, лучше так же его прокидывать

2024-11-01 08:18 UTC, s-skubedin commented on src/components-ui/sidebar/sidebar.tsx
> +const Sidebar = ({ users, handleSelectedUser }: SidebarProps) => {
**suggestion:** Я бы предложил не привязываться к именам, сделать их более нейтральными, так как это UI компонент. Например, `list` или `items` ... , `handleSelected` ...

2024-11-01 08:18 UTC, s-skubedin commented on src/components-ui/sidebar/sidebar.tsx
> +export default memo(Sidebar);
**issue:** memo избыточно.
В пропсах у тебя функция и массив, то есть тебе чтобы мемо работало надо еще мемоизировать пропсы, но не всегда это делают. Тогда получается что мемо будет делать логику, которая заведомо не сработает. Ты можешь перенести ответственность за мемоизацию - пользователям компонента. Если им надо мемоизировать, они сами это сделают.
Например
```jsx
import { memo } from 'react';
import { SideBar as SB } from 'ui-kit';

const SideBar = memo(SB);

function App() {
  return <SideBar />;
}
```

2024-11-01 08:18 UTC, s-skubedin commented on src/components/question-list/question-list.module.css
> +  background-color: var(--backgraund-color);
**typo:** Ошибка в слове `background`

2024-11-01 08:18 UTC, s-skubedin commented on src/components/question-list/question-list.tsx
>    if (questions) {
**issue:** А если нет questions? Что тогда рисуется?
Стоит полностью логику прописывать.
Например,

```jsx
if (!questions || !topic) <div>Select topic and user</div>

return (
  <ul className={styles.list}>
    {questions.map((question, idx) => (
      <QuestionItem
        question={question}
        key={question.id}
        idx={idx}
        handleUpdateQuestion={handleUpdateQuestion}
      />
    ))}
    <li>
      <textarea
        onBlur={handleAddQuestion}
        ref={textQuestionRef}
        className={styles.textarea}
        placeholder="Create new question"
      />
    </li>
  </ul>
)
```

2024-11-01 08:18 UTC, s-skubedin commented on src/pages/main-page.module.css
> +  --light-accent-color: #f0ae99;
**note:** Цвета лучше разбивать на 2 блока. Первый - названия цвета, второй - его применение.

Например
```scss
:root {
  --dark-jungle-green: #1b1c27;
}

html[data-theme=dark] {
  --background: var(--dark-jungle-green);
}
```

Название цвета взял тут - https://color-name.com
По сочетанию цветов можно глянуть тут - https://encycolorpedia.com/1b1c27

2024-11-01 08:18 UTC, s-skubedin commented on src/pages/main-page.module.css
> +}
**issue:** Дважды указываешь одинаковые стили

2024-11-01 08:18 UTC, s-skubedin commented on src/store/question.ts
> +          : await fetchCreateTopicQuestion(text, topicId);
**issue:** Слишком сложное выражение получается. Перенеси await в начало, ожидай результат выполнения тернарника

2024-11-02 07:50 UTC, vkarelina commented on src/App.module.css
> +* {
todo: сделаю в следующем pr

2024-11-02 07:55 UTC, vkarelina commented on src/api/questions.ts
> +  const response: AxiosResponse<Question[]> = await api.get(
question: Есть ли смысл писать serializer/validator на фронте, если бэк возвращает данные которые уже преобразованы через class-transformer и валидируются DTO на бэке?

2024-11-02 12:00 UTC, vkarelina commented on src/pages/main-page.module.css
> +  --light-accent-color: #f0ae99;
todo: Пока что добавила только цвета для темной темы, можно сделать переключение тем, но уже в другом pr

2024-11-02 12:20 UTC, s-skubedin approved these changes

2024-11-02 12:55 UTC, merged