Feature/answers
vkarelina/q-stats__frontend pull request #7
Opened 2024-11-13 11:40 UTC by ysimakina

Added a answers table. 
Added a method in question store to change the answer status.

2024-11-13 12:41 UTC, vkarelina commented on src/components-ui/list-item/list-item.module.css
> +  color: white;
suggestion: Используй переменную из палитры, там вроде есть белый --white

2024-11-13 12:44 UTC, vkarelina commented on src/components/answers-table/answers-table.tsx
> +  const isAnswers = questions.some((q) => q.answers);
suggestion: Лучше использовать более понятные названия для параметров функции

2024-11-13 12:50 UTC, vkarelina commented on src/components/answers-table/answers-table.tsx
> +    if (getShortDate(createdAt) !== getShortDate(new Date())) {
suggestion: Можно написать короче

if (getShortDate(createdAt) !== getShortDate(new Date())) return;

2024-11-13 13:01 UTC, vkarelina commented on src/components/answers-table/answers-table.tsx
> +                    className={
suggestion: Можно использовать classnames

```
className={cn({
  [styles.cellWithBorder]: index < uniqueDates.length - 1,
  [styles.cellWithoutBorder]: index >= uniqueDates.length - 1,
})}
```

2024-11-13 14:28 UTC, vkarelina commented on src/store/question.ts
> +        set((state) => {
suggestion: Можно деструктурирзацией достать поле  
```set({questions}) => {}```
Либо получить выше массив со стейта 
```
const questions = get().questions
```

2024-11-14 08:01 UTC, s-skubedin requested changes

2024-11-14 08:01 UTC, s-skubedin commented on package.json
> +    "@svgr/webpack": "^8.1.0",
**suggestion:** В проекте vite используется, а не webpack, если не ошибаюсь. Зачем эта зависимость?

2024-11-14 08:01 UTC, s-skubedin commented on src/components/answers-table/answers-table.module.css
> +  padding: 5px 15px;
**suggestion:** Используйте четные значение. Желательно, кратные 4 или 2 в степени

2024-11-14 08:01 UTC, s-skubedin commented on src/components/answers-table/answers-table.module.css
> +}
**issue:** Имеется 2 набора цветов, первый - все возможные цвета, второй - палитра, которая использует цвета из первого. В проекте необходимо использовать второй набор. 

В дальнейшем, при создании тем, меняется второй набор, первый всегда неизменный

2024-11-14 08:01 UTC, s-skubedin commented on src/components/answers-table/answers-table.tsx
> +  const isAnswers = questions.some((q) => q.answers);
Да, но в однострочных лямбда функциях можно использовать сокращения, когда это интуитивно понятно. 
Например, в questions.some понятно, что перебираем вопросы и каждый элемент - вопрос, где первая буква q.
Или sort по всем примерам использует `a` и `b`, а в качестве возвращаемого значения `a - b`, тут можно увидеть порядок сортировки, от `a` до `b`, то есть в порядке возрастания. Можно использовать деструктуризацию в sort, `sort(({ someField: a }, { someField: b }) => a - b)`.

2024-11-14 08:01 UTC, s-skubedin commented on src/components/answers-table/answers-table.tsx
> +    );
**issue:** Если в функцию передается больше 3-х аргументов, то стоит передавать объект. Ключи своим именем будет помогать определять необходимые данные для функции, нет зависимости от порядка

2024-11-14 08:01 UTC, s-skubedin commented on src/components/answers-table/answers-table.tsx
> +                  : parseDate(date);
**suggestion:** Стоит разбить компонент на более мелкие, например, Head, Body, Row, Question, Answer ...

2024-11-14 08:01 UTC, s-skubedin commented on src/components/answers-table/answers-table.tsx
> +  };
**suggestion:** Создание данных для рендера стоит делать при получении данных, то есть сразу после ответа на запрос, а не на каждый рендер

2024-11-14 08:01 UTC, s-skubedin commented on src/components/answers-table/answers-table.tsx
> +  };
**suggestion:** Функции, которые помогают работать с данными, лучше выносить в `helpers`

2024-11-14 08:01 UTC, s-skubedin commented on src/components/question-list/question-list.module.css
> +  padding: 33px 40px;
**suggestion:** Используй кратные значения

2024-11-14 13:59 UTC, ysimakina commented on src/components/answers-table/answers-table.tsx
> +  };
Имеешь ввиду сделать это в сторе при получении всех вопросов?

2024-11-15 11:50 UTC, s-skubedin requested changes

2024-11-15 11:50 UTC, s-skubedin commented on src/App.module.css
> +  --right-icon-color: var(--green);
**typo:** Правый? Лучше `correct`

2024-11-15 11:50 UTC, s-skubedin commented on src/App.module.css
> +  --not-clicked-icon-color: var(--grey);
**typo:** not-clicked? Может `inactive`? Или `disabled`, `default`?

2024-11-15 11:50 UTC, s-skubedin commented on src/components-ui/answer-container/answer-container.module.css
> +  background-color: var(--dark-jungle-green);
**suggestion:** Стоит из второго набора цветов брать переменны

2024-11-15 11:50 UTC, s-skubedin commented on src/components-ui/answer-container/answer-container.tsx
> +  const isAnswers = questions.some((q) => q.answers);
**issue:** Вычисления на каждый рендер

2024-11-15 11:50 UTC, s-skubedin commented on src/components-ui/answer-container/answer-container.tsx
> +  const isAnswers = questions.some((q) => q.answers);
**polish:** Тут не `являются`, а `имеются`. `hasAnswers`

2024-11-15 11:50 UTC, s-skubedin commented on src/components-ui/answer-container/answer-container.tsx
> +      const params = {
**suggestion:** Константа избыточна

2024-11-15 11:50 UTC, s-skubedin commented on src/components-ui/answer-container/answer-container.tsx
> +        refreshQuestions: isAnswers ? undefined : refreshQuestions,
**suggestions:** Не стоит передавать функцию в функцию, которая будет или не будет ее вызывать по ее наличию.

fetchUpdateAnswerStatus - отвечает только за получение ответа, тут нет нигде метки, что она еще будет какую-то функцию вызывать.
Стоит вызывать обновление вопросов после изменения ответа. 
```ts
updateAnswer(params);
refreshQuestions();
```

2024-11-15 11:50 UTC, s-skubedin commented on src/components-ui/answer-container/answer-container.tsx
> +              [styles.filledGray]: currentStatus !== true,
**issue:** Сравнение с `true`? -_-

2024-11-15 11:50 UTC, s-skubedin commented on src/components-ui/table-body/table-body.tsx
**issue:** Это не UI.
UI компоненты имеют логику, пропсы, название нейтральные, они не делают бизнес логики. Вернее, могут делать бизнес-логику, если это обосновано частым использованием и помечено в названии..
UI компоненты не взаимодействуют с внешним миром, только в рамках папки UI

2024-11-18 08:38 UTC, s-skubedin approved these changes

2024-11-18 08:53 UTC, vkarelina approved these changes

2024-11-18 09:10 UTC, merged